#!/bin/bash

v=(cube sphere cylinder cone torus opencylinder opencube plane circle capsule)
n=$( rand2 0 9 )

s geo anim turn 0 0 0
s geo anim scaleto 1 1 1 12
s geo anim turn 0 0 $( rsr 1 )      
morph geo 500 1
s geo anim turn 0 1 4      
morph geo 500 1
s geo gs2 shape ${v[$n]}
morph geo 500 1      
morph geo 500 1
morph geo 500 1
s geo gs2 shape ${v[$n]}
morph geo 500 1     
s geo mesh line_width 20
s geo material mat_emission .02 .02 .02
s light minpos -7
s light maxpos 7 
s light atten_const .5
s light atten_const 1.5
s light atten_const 2.0
s geo mesh line_width 10
s geo anim turn $( rsr 1 ) $( rsr 1 ) $( rsr 1 )
s geo anim turn $( rsr 1 ) $( rsr 1 ) 2
morph geo 500 1                        
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
s geo gs1 dim 100 100
s geo gs2 dim 100 100
s geo mesh line_width 2.5

