#!/bin/bash

v=(cube sphere cylinder cone torus opencylinder opencube plane circle capsule)
n=$( rand2 0 9 )

geo anim turn 0 0 0
geo anim scaleto 1 1 1 12
geo anim turn 0 0 $( rsr 1 )      
morph geo 500 1
geo anim turn 0 1 4      
morph geo 500 1
geo gs2 shape ${v[$n]}
morph geo 500 1      
morph geo 500 1
morph geo 500 1
geo gs2 shape ${v[$n]}
morph geo 500 1     
geo mesh line_width 20
geo material mat_emission .02 .02 .02
light minpos -7
light maxpos 7 
light atten_const .5
light atten_const 1.5
light atten_const 2.0
geo mesh line_width 10
geo anim turn $( rsr 1 ) $( rsr 1 ) $( rsr 1 )
geo anim turn $( rsr 1 ) $( rsr 1 ) 2
morph geo 500 1                        
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
morph geo 500 1
geo gs1 dim 100 100
geo gs2 dim 100 100
geo mesh line_width 2.5

