#!/bin/bash

# Source: https://gist.github.com/SebastianGrans/7b6368624352795a8abb023ed0f520fd


if [ -t 0 ]; then stty -echo -icanon -icrnl time 0 min 0; fi

count=0
keypress=''
while [ "x$keypress" = "x" ]; do
  	echo -e \\b\\b\\b\\b\\b\\b\\b\\b`date +%T`\\c
	sleep 1
  	keypress="`cat -v`"
done

if [ -t 0 ]; then stty sane; fi

echo ""
exit 0
