#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head2 NAME

=begin html
 <a href="https://magfoto.xyz">Hello Monde</a>
=end html

=head1 SYNOPSIS



=head1 OPTIONS

=head1 DESCRIPTION



=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
