#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

automata - automatic iteration

=head1 SYNOPSIS

automata [ sleep/rate ]  [ command(s) ]

=head1 OPTIONS

=head1 DESCRIPTION

automatically iterates at a specified rate a set of commands indefinitely or until the process is manually ended.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2022 Marcus A. Gordon

=cut
END_OF_DOCS
