#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

clock - real-time clock

=head1 SYNOPSIS

Displays a real-time clock in HR:MIN:SEC format.

=head1 OPTIONS

=head1 DESCRIPTION



=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2022 Marcus A. Gordon

=cut
END_OF_DOCS
