#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

count - counter

=head1 SYNOPSIS

Counter that counts until the specified target is reached.


=head1 OPTIONS

Adding a "/" signals to take the next value as the counting "breath", default set to 1.

e.g. : count 5 / 2 - this statement counts to 5 with 2 second intervals between every increment.


=head1 DESCRIPTION

Counter that counts until the specified target is reached.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2022 Marcus A. Gordon

=cut
END_OF_DOCS
