#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

crow - experimental command for controlling Crow sound computer

=head1 SYNOPSIS

crow [ lua code ]

=head1 OPTIONS

=head1 DESCRIPTION

The Crow sound computer interprets Lua code, and the sigv crow command is a prototype for writing and automatically uploading Lua code via USB to Crow module.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
