#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

ice - experimental command for controlling IceCube volumetric display

=head1 SYNOPSIS

ice  [ agent ] [ param 1 ] [ param 2 ] [ param 3 ] [ param 4 ] 

=head1 OPTIONS

=head1 DESCRIPTION

ice is an experimental command that sends a custom message to an OSC module within the IceCube display.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
