#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

morph0 - sigv/bash command for carrot (^) transition or transform

=head1 SYNOPSIS

morph [ object ] [ iterations ] [ sleep ]

=head1 OPTIONS



=head1 DESCRIPTION

The morph command currently targets (^) equipped objects, such as geo, proc, and lz, and interpolates randomized value ranges (negative and positive normalized floats).  Related commands include morph and morpha.

=head1 EXAMPLES

morph0 geo 250 1 (transforms geo with 1 second intervals)

=head1 NOTES

morph is dependent on the rsr command for generating normalized values to transition to.

=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
