#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

o - direct Orca UDP/OSC message

=head1 SYNOPSIS

o [ orca commands ]

=head1 OPTIONS

=head1 DESCRIPTION

The o command uses the terminal's nc utility to send UDP messages to Orca live coding environment.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
