#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

ofx - experiment command for oFx visual coding

=head1 SYNOPSIS



=head1 OPTIONS

=head1 DESCRIPTION

The oFx command targets a visual live coding prototype involving openFrameworks, Lua, and Pure Data.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
