#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

randx - generates a random number

=head1 SYNOPSIS



=head1 OPTIONS

=head1 DESCRIPTION

The randx command generates a random number within the specified beginning and end range.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
