#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

rand - generate a random integer

=head1 SYNOPSIS

rand [ end range ]

=head1 OPTIONS

=head1 DESCRIPTION

The rand command generates a positive integer between 0 and value specified.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
