#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

rfi - utility for reading file content iteratively by line

=head1 SYNOPSIS

rfi _examples .5

=head1 OPTIONS

=head1 DESCRIPTION

The rfi utility reads file content line by line at specified rate.

=head1 EXAMPLES



=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
