#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

sfor - C-style conditional loop operator

=head1 SYNOPSIS

sfor [ interations ]  [ command ] [ sleep ]

=head1 OPTIONS

=head1 DESCRIPTION



=head1 EXAMPLES

sfor 3 "randx 2 45" .5

=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2023 Marcus A. Gordon

=cut
END_OF_DOCS
