#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

sigv - main function for sigv mini-language and CLI utility.

=head1 SYNOPSIS

sigv [ flag ] [ *file ]

=head1 OPTIONS

-b = jump to sigv project directory and list contents (command list)

-m = create new man page in project directory

-j = launch sigv.js

-- config = open/edit sigv configuration (this file)

-- examples = list of sample instructions


=head1 DESCRIPTION

Main sigv mini-language command for initiating sigv environments (i.e. bash/sigv and sigv.js).  Mainly used to author the system for performance, experiemnt, and session specifications.

=head1 EXAMPLES

=head1 NOTES

Eventually, this element will also trigger an automated process to compose new man pages faster, and automatically implement them into the man search path.

=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2022 Marcus A. Gordon

=cut
END_OF_DOCS
