#!/usr/bin/env bash

: <<'END_OF_DOCS'

=begin html

sigv/bash

<hr/>

=end html

=head3 Command

gen


=head4 Command Type

bash

=head4 Description

main number generator based on Bash seq command


=head5 Type I Operation

amplifier


=head5 Type II Operation

shaper


=head5 Type III Operation

=head5 Type IV Operation


=head4 License and Copyright

MIT License

=begin html

&copy; 2024 Marcus A. Gordon

=end html

=cut

END_OF_DOCS
