#!/usr/bin/env bash

: <<'END_OF_DOCS'

=head1 NAME

timer - seconds timer

=head1 SYNOPSIS

timer [ integer ]

=head1 OPTIONS

=head1 DESCRIPTION

This utility starts a timer and prints out each second.

=head1 EXAMPLES

: timer 7

0
1
2
3
4
5
6

=head1 NOTES



=head1 LICENSE AND COPYRIGHT

MIT License

Copyright (c) 2022 Marcus A. Gordon

=cut
END_OF_DOCS
