#!/bin/bash

# format: mod p 4 1

l1=$(rand2 0 12)
l2=$(rand2 12 24)
l3=$(rand2 24 26)
l4=$(rand2 36 48)
l5=$(rand2 48 60)

if [[ $1 == "p" && $4 == "1" ]]
then
 iter $2 $3 "mod $l1 60 $3"
elif [[ $1 == "p" && $4 == "2" ]]
 then
  iter $2 $3 "mod $l2 60 $3"
elif [[ $1 == "p" && $4 == "3" ]]
 then
  iter $2 $3 "mod $l3 60 $3"
elif [[ $1 == "p" && $4 == "4" ]]
 then
  iter $2 $3 "mod $l4 60 $3"
elif [[ $1 == "p" && $4 == "5" ]]
 then
  iter $2 $3 "mod $l5 60 $3"
else
  sendmidi dev Studio ch 1 on ${1} ${2}
  sleep ${3}
  sendmidi dev Studio ch 1 off ${1} ${2}
fi
