#!/bin/bash

s geo anim turn 0 0 0
s geo anim scaleto 1 1 1 12
s geo anim turn 0 0 4      
morph 100 1
s geo anim turn 0 1 4      
morph geo 100 1
s geo gs2 shape torus
morph geo 100 1      
morph geo 100 1
morph geo 100 1
s geo gs2 shape cone
morph geo 100 1     
s geo mesh line_width 20
s geo material mat_emission .02 .02 .02
s light minpos -7
s light maxpos 7 
s js light
s light atten_const .5
s light atten_const 1.5
s light atten_const 2.0
s geo anim turn -.2 -.7 0
s geo anim turn -.2 -.7 2
morph geo 100 1                        
morph geo 100 1
morph geo 100 1
morph geo 100 1
morph geo 100 1
morph geo 100 1
morph geo 100 1
s geo gs1 dim 100 100
s geo gs2 dim 100 100
s geo mesh line_width 2.5

