#!/bin/bash

l1=$(rand2 0 12)
l2=$(rand2 12 24)
l3=$(rand2 24 26)
l4=$(rand2 36 48)
l5=$(rand2 48 60)
l6=$(rand2 60 72)
l7=$(rand2 72 84)
l8=$(rand2 84 96)
l9=$(rand2 96 108)
l10=$(rand2 108 120)


case "$1" in
  "kick") chann="opz 1"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
      "5" ) iter $2 $3 "$chann $l5 60 $3" ;;
      "6" ) iter $2 $3 "$chann $l6 60 $3" ;;
      "7" ) iter $2 $3 "$chann $l7 60 $3" ;;
      "8" ) iter $2 $3 "$chann $l8 60 $3" ;;
    esac
  ;;
  "snare") chann="opz 2"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "perc") chann="opz 3"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "sample") chann="opz 4"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "bass") chann="opz 5"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "lead") chann="opz 6"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "arp") chann="opz 7"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "chord") chann="opz 8"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "fx1") chann="opz 9"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "fx2") chann="opz 10"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "tape") chann="opz 11"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "master") chann="opz 12"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "perform") chann="opz 13"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
  "module") chann="opz 14"
    case "$4" in
      "1" ) iter $2 $3 "$chann $l1 60 $3" ;;
      "2" ) iter $2 $3 "$chann $l2 60 $3" ;;
      "3" ) iter $2 $3 "$chann $l3 60 $3" ;;
      "4" ) iter $2 $3 "$chann $l4 60 $3" ;;
    esac
  ;;
esac


# MIDI Mapping for OP-Z
sendmidi dev OP-Z ch ${1} on ${2} ${3}
sleep ${4}
sendmidi dev OP-Z ch ${1} off ${2} ${3}
