#!/bin/bash

b0 anim scaleto 2 2 2 20; sleep 20; b0 anim scaleto 1 1 1 5; sleep 5; b0 anim turn 0 -14 0; sleep 10; b0 anim turn 0 5 0; sleep 3; b0 anim turn 0 20 0; sleep 4; b0 anim scaleto .5 .5 .5 10; sleep 10; b0 anim turn 0 0 0;
