#!/bin/bash

if [[ "$1" == "-l" ]]
then
  echo "Launching LTTP:// standalone..."
  open $HOME/lttp/lttp.maxpat
  echo "Commands: lttp [ route ] [ value ]"
  echo "Routes: sub activate metro drunk"
  echo "Sub-routes: sub > "
else
  s lttp "$*"
fi
